# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_testWindow(object):
    def setupUi(self, testWindow):
        testWindow.setObjectName("testWindow")
        testWindow.setFixedSize(331, 146)
        self.centralwidget = QtWidgets.QWidget(testWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.push)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 40, 100, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setStyleSheet("font-size:18px;font-family: Times New Roman;font-weight: bold;")
        testWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(testWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 21))
        self.menubar.setObjectName("menubar")
        testWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(testWindow)
        self.statusbar.setObjectName("statusbar")
        testWindow.setStatusBar(self.statusbar)

        self.retranslateUi(testWindow)
        QtCore.QMetaObject.connectSlotsByName(testWindow)

    def push(self):
        self.label.setText("WORKING")

    def retranslateUi(self, testWindow):
        _translate = QtCore.QCoreApplication.translate
        testWindow.setWindowTitle(_translate("testWindow", "TestGUI"))
        self.pushButton.setText(_translate("testWindow", "PUSH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    testWindow = QtWidgets.QMainWindow()
    ui = Ui_testWindow()
    ui.setupUi(testWindow)
    testWindow.show()
    sys.exit(app.exec_())
